AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "novacloud_client.gemspec"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
